name: Digraphs
version: 0.12.1
date: 2018-04-26
description: |
    Graphs, digraphs, and multidigraphs in GAP

authors:
    - name: J. De Beule
      url: http://homepages.vub.ac.be/~jdbeule/
    - name: J. Jonusas
      url: http://www-groups.mcs.st-andrews.ac.uk/~julius/
    - name: J. D. Mitchell
      url: http://goo.gl/ZtViV6
    - name: M. Torpey
      url: http://www-groups.mcs.st-andrews.ac.uk/~mct25/
    - name: W. A. Wilson
      url: http://www-groups.mcs.st-andrews.ac.uk/~waw7/

maintainers:
    - name: J. D. Mitchell
      url: http://goo.gl/ZtViV6

contributors:
    - name: S. Burrell
      url: mailto:sb235@st-andrews.ac.uk
    - name: L. Elliott
      url: mailto:le27@st-andrews.ac.uk
    - name: C. Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk
    - name: M. Pfeiffer
      url: https://www.morphism.de/~markusp/
    - name: C. Russell
      url: mailto:cr66@st-andrews.ac.uk
    - name: F. Smith
      url: mailto:fls3@st-andrews.ac.uk

GAP: ">=4.8.2"

needed-pkgs:
    - name: "io"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.7.5"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.5"
      url: "http://www.maths.qmul.ac.uk/~leonard/grape/"
    - name: "nautytracesinterface"
      version: ">=0.2"
      url: "http://TODO/"

www: https://gap-packages.github.io/Digraphs
readme: README.md
packageinfo: https://gap-packages.github.io/Digraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Digraphs/releases/download/v0.12.1/digraphs-0.12.1.tar.gz

abstract: |
    The <b>Digraphs</b> package is a <b>GAP</b> package for digraphs and multidigraphs.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
